# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7ec1a159891f4fa84183c24c3a923eba4682a42e6375f8d795b269dc4c2bc0b8a815c558ce0e9504de8fe12c2137ffcbe6e485d62255463cc24c121ee05f8ae

test:
  secret_key_base: 12f2cb3709ca421c89661a37d47802d263bfa22dbbda2ac3bb7cb9b9bf81b077e507b3a678dd830dedaddcf06c2db4ca2834a1dc448ce8674139eadf1a6d3833

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
